# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: a15t/bottle/agent/v1/service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'a15t/bottle/agent/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from a15t.bottle.agent.v1 import types_pb2 as a15t_dot_bottle_dot_agent_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"a15t/bottle/agent/v1/service.proto\x12\x14\x61\x31\x35t.bottle.agent.v1\x1a a15t/bottle/agent/v1/types.proto\"\x85\x02\n\x18PrimaryThreadChatRequest\x12.\n\x07message\x18\x01 \x01(\x0b\x32\x1d.a15t.bottle.agent.v1.Message\x12.\n\x07history\x18\x02 \x03(\x0b\x32\x1d.a15t.bottle.agent.v1.Message\x12+\n\x06\x66\x61\x63\x65ts\x18\x03 \x03(\x0b\x32\x1b.a15t.bottle.agent.v1.Facet\x12\x0e\n\x06locale\x18\x04 \x01(\t\x12\x10\n\x08timezone\x18\x05 \x01(\t\x12:\n\x0erecall_history\x18\x06 \x03(\x0b\x32\".a15t.bottle.agent.v1.MessageGroup\"b\n\x1fPrimaryThreadChatProjectCreated\x12.\n\x07project\x18\x01 \x01(\x0b\x32\x1d.a15t.bottle.agent.v1.Project\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x98\x01\n\x19PrimaryThreadChatResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12N\n\x0fproject_created\x18\x02 \x01(\x0b\x32\x35.a15t.bottle.agent.v1.PrimaryThreadChatProjectCreated\x12\x1a\n\x12\x65val_metadata_json\x18\x03 \x01(\t2\x86\x01\n\x0c\x41gentService\x12v\n\x11PrimaryThreadChat\x12..a15t.bottle.agent.v1.PrimaryThreadChatRequest\x1a/.a15t.bottle.agent.v1.PrimaryThreadChatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a15t.bottle.agent.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRIMARYTHREADCHATREQUEST']._serialized_start=95
  _globals['_PRIMARYTHREADCHATREQUEST']._serialized_end=356
  _globals['_PRIMARYTHREADCHATPROJECTCREATED']._serialized_start=358
  _globals['_PRIMARYTHREADCHATPROJECTCREATED']._serialized_end=456
  _globals['_PRIMARYTHREADCHATRESPONSE']._serialized_start=459
  _globals['_PRIMARYTHREADCHATRESPONSE']._serialized_end=611
  _globals['_AGENTSERVICE']._serialized_start=614
  _globals['_AGENTSERVICE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
